name: Get current git revision
on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Get revision
    runs-on: ubuntu-20.04
    steps:
      - name: Get
        run: |
          set -e

          echo "Repository: ${{ github.repository }}"

          # Version 1
          CMD="git ls-remote https://github.com/${{ github.repository }} | head -1 | sed \"s/HEAD//\" | cut -c 1-7"
          VREV1=eval $CMD || true
          echo "Version 1: $VREV1"

          # Version 2
          VREV2=`git ls-remote https://github.com/${{ github.repository }} | head -1 | sed "s/HEAD//" | cut -c 1-7`
          echo "Version 2: $VREV2"

          # Version 3
          VREV3=$(git ls-remote https://github.com/${{ github.repository }} | head -1 | sed "s/HEAD//" | cut -c 1-7)
          echo "Version 3: $VREV3"

          # Version 4
          CMD="git ls-remote https://github.com/${{ github.repository }} | head -1 | sed s/HEAD// | cut -c 1-7"
          VREV4=eval $CMD || true
          echo "Version 4: $VREV4"
